base_url = "www.bigelectrons.com"
title = "bigelectrons"
default_language = "en"
highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "links", fees = true, paginate_by = 10 },
	{ name = "tags", fees = true, paginate_by = 10 },
]
languages = []
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[markdown]
render_emoji = true

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[translations]

[extra]
# To enable rendering of KaTeX math formulas
katex.enabled = true
katex.auto_render = true

navbar_items = [
	{ url = "$BASE_URL/", name = "Home" },
	{ url = "$BASE_URL/posts", name = "Posts" },
	{ url = "$BASE_URL/navo", name = "Navo" },
	{ url = "$BASE_URL/projects", name = "Projects" },
	{ url = "$BASE_URL/links", name = "Links" },
	{ url = "$BASE_URL/categories", name = "Categories" },
	{ url = "$BASE_URL/tags", name = "Tags" }
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "joesan"

[extra.social]
github = "joesan"
youtube = "UCWj0B-W_fJvQqDG6ILyGgrA"
#instagram = "joesandech"
stackoverflow = "3102968"
