name: Build and Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'backup/**'
      - '**/*.draft.md'
      - 'util/**'
      - 'help/**'
      - '.gitignore'
      - 'LICENSE'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check HTTP Links
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: -v "content/**/*.md"
          # This action below creates an issue automatically
          #- name: Create Issue From File
          # uses: peter-evans/create-issue-from-file@v2
          #with:
          # title: Link Checker Report
          #content-filepath: ./lychee/out.md
          #labels: report, automated issue

  listDraftContent:
    needs: linkChecker
    runs-on: macos-latest
    if: github.ref == 'refs/heads/master'
    env:
      TARGET_BRANCH: draft-status

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Scala
        run: |
          brew install scala
          git config --global user.email "workflow-bot@bigelectrons.com"
          git config --global user.name "workflow-bot"

      - name: Save script before switching branch
        run: |
          mkdir -p temp_scripts
          cp .github/scripts/list_draft_content temp_scripts/
          chmod +x temp_scripts/list_draft_content

      - name: Create orphan branch and restore script
        run: |
          git checkout --orphan $TARGET_BRANCH
          git rm -rf . || true
  
          mkdir -p .github/scripts
          mv temp_scripts/list_draft_content .github/scripts/

      - name: Run Draft Content Script
        run: |
          echo "Running script to generate draftStatus.txt..."
          bash .github/scripts/list_draft_content content draftStatus.txt
          echo "Output:"
          cat draftStatus.txt

      - name: Commit and push draftStatus.txt
        run: |
          rm -f README.md
          echo "TEMPORARY BRANCH, PLEASE NAVIGATE TO THE MASTER BRANCH" > README.md
          git add draftStatus.txt README.md
          git commit -m "generated draftStatus.txt"
          git push --set-upstream origin $TARGET_BRANCH --force

  deploy:
    runs-on: ubuntu-latest
    needs: linkChecker
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) tt + another test
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.120.0
          #hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
