name: Build and Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'backup/**'
      - '**/*.draft.md'
      - 'util/**'
      - 'help/**'
      - '.gitignore'
      - 'LICENSE'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check HTTP Links
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: -v "content/**/*.md"
          # This action below creates an issue automatically
          #- name: Create Issue From File
          # uses: peter-evans/create-issue-from-file@v2
          #with:
          # title: Link Checker Report
          #content-filepath: ./lychee/out.md
          #labels: report, automated issue

  listDraftContent:
    needs: linkChecker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      TARGET_BRANCH: draft-status

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools and configure git
        run: |
          brew install scala || echo "brew not available on ubuntu, skipping"
          git config --global user.email "workflow-bot@bigelectrons.com"
          git config --global user.name "workflow-bot"

      - name: Run draft status script (on master branch)
        run: |
          chmod +x .github/scripts/list_draft_content.sh
          .github/scripts/list_draft_content.sh content draftStatus.txt
          echo "Output of draftStatus.txt:"
          cat draftStatus.txt

      - name: Preserve files before orphaning
        run: |
          mkdir orphan_temp
          mv draftStatus.txt orphan_temp/
          echo "TEMPORARY BRANCH, PLEASE NAVIGATE TO THE MASTER BRANCH" > orphan_temp/README.md
          cp .github/scripts/list_draft_content.sh orphan_temp/

      - name: Create orphan branch and commit
        run: |
          git checkout --orphan $TARGET_BRANCH
          git rm -rf . || true

          mkdir -p .github/scripts
          mv orphan_temp/list_draft_content.sh .github/scripts/
          mv orphan_temp/draftStatus.txt .
          mv orphan_temp/README.md .

          git add draftStatus.txt README.md
          git commit -m "generated draftStatus.txt"
          git push --set-upstream origin $TARGET_BRANCH --force

  deploy:
    runs-on: ubuntu-latest
    needs: linkChecker
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) tt + another test
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.120.0
          #hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
